### ISSUE TITLE
Observed deployment failures at hyscale stating the cluster has not enough space to accommodate new services

### ISSUE THREAD

**Issue by satish1225** [hyscale/hyscale#153]
Summary : 
Observed deployment failures at hyscale stating the cluster has not enough space to accommodate new services. With kubectl I found the services are up and running after a few seconds.

**Steps to replicate:**
1. Try to deploy app to some cluster where the utilisation is almost full.
2. Verify the app deployment status

**Expected result:**
App deployment should be succeed

**Actual result:**
[ACTION]  Pod initialization ...............................................................  [FAILED]

**************************                      ERROR                       **************************

[ERROR]  [Failed to initialize pod]
Cannot accomodate new services as the cluster is full. Please contact your cluster administrator to add cluster capacity or deploy to different cluster

**Screenshots/Additional info:**

**Comment by SameeraGrandhi** [comment]
Which cluster are you using? Do you have autoscaling enabled in your cluster?

**Comment by satish1225** [comment]
i am using GKE cluster v1.14 and auto scaling is enabled.
After pod  initialisation failed from the hyscale,  cluster is verified  and observed that all pods are in running state.

**Comment by SameeraGrandhi** [comment]
Deployment waits for 2 mins and exits if the pods are not ready, in such cases the deployment is considered to be failed.

**Comment by tushar-tushar** [comment]
In your case, it seems the cluster capacity became full during deployment as a result pod was not allocated to any node. Which can also be seen from the troubleshooting message. Also, In your case, I'm assuming cluster autoscaling was enabled which added a new node to accommodate the pods as a result later the pod went into ready state when observed through kubectl.
To check your service status after deployment, you can use the [service status command ](https://github.com/hyscale/hyscale/blob/master/docs/hyscale-commands-reference.md#service-status) which also returns the real-time status of the service.

Closing the issue, for now, reopen if you have any query.
