### ISSUE TITLE
App deployment failures observed intermittently in Minikube 1.16 and 1.17 cluster

### ISSUE THREAD

**Issue by satish1225** [hyscale/hyscale#155]
Summary : 
App deployment failures observed intermittently. After sometime the pods are up and running in the kubernetes cluster. Why is the deployment failing from hyscale ? I'm using Minikube 1.16 and 1.17 cluster locally to try these examples hrms.

**Steps to replicate:**
1. Deploy the hspec's of hrdatabase from the examples directory of hrms.
2. Verify the deployment through hyscale deploy service command.

**Expected result:**
App deployment should have been succeeded.

**Actual result:**
[ACTION]  Pod initialization ...............................................................  [FAILED]
**Screenshots/Additional info:**

**Comment by tushar-tushar** [comment]
Was not able to replicate the issue in local machine, with configuration: minikube version: v1.11.0, cluster 1.17 as well as 1.16. All deployments were successful.

Could you retry with the latest version of hyscale as well as minikube to see if the problem still persists?

Closing for now. Please reopen if you are still facing the issue, While reopening do provide the logs as well as troubleshoot message provided by hyscale.
