### ISSUE TITLE
Get apps shows no deployments when replicas are 0

### ISSUE THREAD

**Issue by srujankujmar** [hyscale/hyscale#184]
**Steps to replicate:**
Do a deployment with 0 replicas
**Expected result:**
Get apps should show details of app and service deployed
**Actual result:**
[INFO]  No deployments found on the cluster
**Screenshots/Additional info:**

**Comment by tushar-tushar** [comment]
https://github.com/hyscale/hyscale/pull/183/commits/b32139b530c8f917be67a0568a958cf65fa024ed
