### ISSUE TITLE
Unable to install Hyscale tool in windows 8.1

### ISSUE THREAD

**Issue by chandu54** [hyscale/hyscale#197]
I recently tried to install hyscale using windows power shell. I faced some issues during the process.

Operating system:windows 8.1
Java version : JDK 11.0.7
power shell

 version : 4.0

Please find the attached screenshot for reference.
![Hyscale issue](https://user-images.githubusercontent.com/17500446/83999240-f683e080-a97f-11ea-9f8a-21c9878715c5.PNG)

**Comment by srujankujmar** [comment]
PR - https://github.com/hyscale/hyscale/pull/198 Riased for the issue
