### ISSUE TITLE
Structured Output 

### ISSUE THREAD

**Issue by SameeraGrandhi** [hyscale/hyscale#206]
**Is your feature request related to a problem? Please describe:**
Hyscale currently logs the workflow progress in the standard output format. But in order to act on output like reusing output for other commands integration, integration into some code for all non-human actions. In all these cases parsing will be difficult. 

**Describe the solution you'd like:**
Having a structured/parsable output helps users to act on their needs.

**Additional context:**

This implementation is just a beta version of structured output for deploy command only.
Since HyScale supports only synchronous deployments through commands the output is displayed only after the command has completed its execution. The end-user is subjected to wait for the output in the meantime. Users will experience some kind of inactivity during this time. The structured output is enabled only when user requests with [`--output or -o` ] option during the `hyscale deploy service` command.

This problem will be solved soon with asynchronous deployments.

**Comment by nagachandra-immadisetty** [comment]
@SameeraGrandhi / @srujankujmar can you please update the bash script such that if user gives --output json or -o json in the deploy service command **WORKFLOW_LOGGER_DISABLED** environment variable should be added as true. So that hyscale banner will be invisible in the case of structured output.

**Comment by nagachandra-immadisetty** [comment]
If user requests with -o json or --output json in deploy service command, deployment activity will be shown in a json format.

Ex: hyscale deploy service -f myservice.hspec -f myservice1.hspec -n samplens -a sampleapp -o json
```
{
  "serviceStatus": [
    {
      "exitCode": 201,
      "message": "[Failed to get service address]",
      "name": "myservice"
    },
   {
      "message": "10.11.12.13",
      "name": "myservice1"
    }
  ]
}
