### ISSUE TITLE
Props value changes not reflected in the pod.

### ISSUE THREAD

**Issue by tushar-tushar** [hyscale/hyscale#210]
Summary : 
Whenever user changes a prop value and re-deploys the value is not reflected in the pod env. The config map changes but the pod env value inside the container is not reflected.
---
**Steps to replicate:**
Deploy quickstart go-lang hello world service.
Check props value in pod.
Update props value in service spec and redeploy.
Again check the props value in pod.
**Expected result:**
Pod should have updated prop value.
**Actual result:**
Prop value is not updated in the pod

**Comment by tushar-tushar** [comment]
Queries:
1. What all resources to cover: 
    - Configmap, Secrets, Agents(Config maps, Secrets)...
2. What all data to keep as a checksum: Should it also include the binaryData field?
3. Which hashing algorithm to use - MD5, SHA1?
4. Labels - If labels kept in the pod(through STS/Deployment) then a patch call would be required every time the config map is changed, this will restart the pods?
5. Pod Restart Policy: 
    - Label: If labels kept in the pod(through STS/Deployment) then a patch call would be required every time the config map is changed, this will restart the pods
    - Delete existing
    - Scale down and up, 
    - rollout restart(kubectl command): Internally calls patch API with updated restarted time in the annotation. 
6. Agents config map: Need to restart pod if agent config map value is changed?

**Comment by SameeraGrandhi** [comment]
@tushar-tushar 

1. Need to cover all the entities which are using config maps and secrets that include service props, service secrets, agent props, and agent secrets.

2. Data includes the props, secrets fields of both service and the agents defined for the service. This includes the binary data also because props can have string, file, endpoint types as its values.

3. Both MD5 and SHA1SUM uses the content to hash. So we can use either of them as a use-case. Better to explore the pros and cons on this regard.

4. Labels have certain restrictions on updating stateful sets and deployments and they are not meant to store metadata. It's right to consider annotations for storing these checksums. 

5. Pod Restart Policy is handed over to Kubernetes with this annotation on every update.

6. Since pod is a group of containers we cannot just restart a single container we need to restart the entire pod.

**Comment by tushar-tushar** [comment]
1. Resources to be covered: Config map, Secret( image pull secret not required), Agents(Config maps and secrets)
2. Data format:
    - Config map: { data: "value", binaryData:  "value"}
    - Secret: {data: "value"}
3. SHA1 as it is more secure and we are storing secrets.
4. Using Annotations instead of labels: This follows the earlier policy of keeping required data in annotation like last-applied-config. The annotations will be at pod level, through the template field in STS/Deployment
5. Pod will be automatically restarted as Deployment/STS would be patched on annotation change.
6. Same as 5.

Annotation details:
hyscale.io/<container-name>/props/checksum: SHA1 of { data: "value", binaryData:  "value"}
hyscale.io/<container-name>/secrets/checksum: SHA1 of "value" (Everything under the data field of secret)

For services:
Container name will be the service name

For Agents
Container name will be agent name

**Comment by SameeraGrandhi** [comment]
@tushar-tushar to put your point on a clear note:

Annotations that are to be added to statefulset or deployment as part of the checksum.

`hyscale.io/<container-name>/props/checksum`
`hyscale.io/<container-name>/secrets/checksum`

For primary service, the container name will be the service name
For all agents, the container name will be the agent name itself.

**Comment by tushar-tushar** [comment]
@SameeraGrandhi 
Annotation naming doesn't allow this pattern. Based on docs: Valid annotation keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. 

Instead of slash(/) should I go with dash(-)?
Also will normalize the container name length in case it is larger than 45.

**Comment by SameeraGrandhi** [comment]
In such a case instead of going around the bush it is more clear if we just consider the config map name, the secret name itself like
`hyscale.io/<resource-name>`

**Comment by tushar-tushar** [comment]
In that case, it would be `hyscale.io/configmap, hyscale.io/secrets and hyscale.io/service-<svc>-agent-<agent>-configmap, hyscale.io/service-<svc>-agent-<agent>-secret.` Is that fine?

**Comment by SameeraGrandhi** [comment]
With a single annotation 
`hyscale.io/checksum: SHA1SUM(hspec.props + hspec.secrets + hspec.agents[].props + hspec.agents[].secrets)`
