### ISSUE TITLE
I don't understand the benefits of this project

### ISSUE THREAD

**Issue by orefalo** [hyscale/hyscale#303]
- "K8s complexity" is an over statement  - Developers have a hard time understanding the life/complexity of an Ops guy, it's just like the early ages of window managers SDK.

Are you completely abstracting from k8s? for all use cases? 
Are you solving the complexities around building the docker image?
Are you solving the complexities around logging?
Are you solving the complexities around observability?
Are you solving the complexities around dependencies and deployment strategies?
Are you solving the complexities around debugging?

Sorry, I don't see how your solution helps.
  It's just a facade that poorly criticizes a full featured product at the cost of an opinionated architecture with heavy limitations.

My 2c.

**Comment by DeepikaChary** [comment]
Hi Olivier,

Thank you for your feedback. This project intends to solve deployment complexities faced by developers and DevOps with an app-centric abstraction framework over Kubernetes. Some of the use cases ( building Dockerfile, debugging) you have mentioned are already covered by HyScale, and some are on our roadmap. We are a small team trying to bring K8s close to the dev community. You can read more about our approach towards abstraction [here](https://github.com/hyscale/hyscale/wiki/App-centric-Abstraction)
