### ISSUE TITLE
Failed to get service address error

### ISSUE THREAD

**Issue by Koeng101** [hyscale/hyscale#317]
Summary : 
---
**Steps to replicate:**
- Installed k3s server on a fresh DO droplet
- configured docker registry info + kubectl properly
- ran a test application (Dockerfile of a blog of mine)

**Expected result:**
- Success in deployment

**Actual result:**

```
**************************                SERVICE: koengbio                 **************************


**************************              Dockerfile Generation               **************************

[ACTION]  Generating Dockerfile ............................................................  [SKIPPED]

**************************               Image build and Push               **************************

[ACTION]  Building image ...................................................................  [DONE]
[ACTION]  Tagging image ....................................................................  [DONE]
[ACTION]  Pushing image ....................................................................  [DONE]

**************************               Manifest Generation                **************************

[ACTION]  Generating manifest for Secret ...................................................  [DONE]
[ACTION]  Generating manifest for Deployment ...............................................  [DONE]
[ACTION]  Generating manifest for Service ..................................................  [DONE]
[ACTION]  Generating manifest for HorizontalPodAutoscaler ..................................  [DONE]

**************************                    Deployment                    **************************

[ACTION]  Applying Secret ..................................................................  [DONE]
[ACTION]  Applying Service .................................................................  [DONE]
[ACTION]  Applying Deployment ..............................................................  [DONE]
[ACTION]  Applying HorizontalPodAutoScaler .................................................  [DONE]

**************************        Waiting for deployment completion         **************************

[ACTION]  Pod initialization ...............................................................  [DONE]
[ACTION]  Pod creation .....................................................................  [DONE]
[ACTION]  Pod readiness ....................................................................  [DONE]
[ACTION]  Waiting for service IP ...........................................................  [FAILED]

**************************                      ERROR                       **************************

[ERROR]  [Failed to get service address]
```

I suspect this may be something about how k3s handles service IPs, but I am not sure. Any thoughts on troubleshooting directions?

**Comment by vijaySamanuri** [comment]
Hi Koeng101,

if `external` is set as true in hspec yaml, hyscale would try to create service resource in kubernetes with `type: LoadBalancer`

And k3s supports service type LoadBalancer and gives you an External IP by creating klipper LoadBalancer on demand. For more details you can check this link

Can you check whether klipper lb is getting created successfully in the respective namespace?
You can find out using the following commands. Also please let us know the output of the same

`kubectl describe nodes`
`kubectl get pods -n <your-namespace>`
You should see klipper lb pod running for your service by name svclb-******
`kubectl describe pod svclb-*** -n <your-namespace>`

**Comment by vijaySamanuri** [comment]
>     * Installed k3s server on a fresh DO droplet

Also try setting environment variable `HYS_LB_READY_TIMEOUT` to some 5 mins as you mentioned it is on Digital Ocean. 
DO would take more time to arrange loadbalancer ip address.

`HYS_LB_READY_TIMEOUT` - hyscale waiting time to get the service lb details.

We continuously poll and wait for service lb details with a default time-out of 90 seconds.

Digital Ocean might be taking more than this. Please try `HYS_LB_READY_TIMEOUT` setting of some 5 mins and try redeploying it using `hyscale deploy`

`export HYS_LB_READY_TIMEOUT=300000` or put it in your bash profile.

**Comment by Koeng101** [comment]
Thanks for the kubectl describe! Turns out that the node did not have an open port for the port I requested (port 80). 

The error:
```
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.
```

It seems that that port is used by traefik in k3s - which appears to conflict with the external port that hyscale is setting up. I tried figuring out how to get around this (with this for example https://opensource.com/article/20/3/kubernetes-traefik), but it seems like modifications are necessary within the .yaml configuration file itself, which I believe hyscale is in charge of. Is there anyway to use traefik with hyscale, or is this unsupported?

**Comment by vijaySamanuri** [comment]
Looks like you are using 80 port inside your application and k3s tries to create klipper lb with the same port (with a scheduling node constraint port 80 being free) which was already taken by traefik ingress controller.

Ingress support is in our immediate roadmap which should solve this problem.  

But for the time being you can try custom snippets feature in hspec. Refer k8s snippets feature doc [here](https://github.com/hyscale/hyscale/blob/master/docs/custom-k8s-snippets.md)

We can make use of any other free port in kubernetes service yaml. So prepare a k8s service snippet file with the below contents.

```yaml
kind: Service
metadata: 
  name: <your-service-name>
spec: 
  ports:
  - name: "80-tcp"
    port: 8080
    protocol: "TCP"
    targetPort: 80
  ```
Note: Assuming 8080 is free or try any other free port.

And then modify hspec pointing to the above snippet file:

```
k8sSnippets:
<path-to-service-snippet.yaml>
```

Add the above block to end of your hspec file then redeploy using `hyscale deploy`


For example:

Let's say you copied the above service snippet yaml in a file by name `service-patch.yaml` and placed it next to your `hspec` file then modify your `hspec` adding k8sSnippets section.

```
k8sSnippets:
service-patch.yaml 
```
