### ISSUE TITLE
Log Files are not zipped after a set size and keeps on appending to a single file

### ISSUE THREAD

**Issue by iamTheL** [hyscale/hyscale#322]
Summary : 
---
**Steps to replicate:**
The log files which hyscle writes are not rolled and rotated either. This makes the log file massive.

**Expected result:**
The log files are supposed to be zipped say after 10Mb and rolled up. 

**Actual result:**
The log files grows to several MBs leading to inefficient space management

**Screenshots/Additional info:**
![image](https://user-images.githubusercontent.com/2375346/95970567-bbae1f80-0e2d-11eb-8b14-99fc3441962e.png)

**Hyscale version:**
HyScale Version 0.9.8.0 "First Light", build 38b6df3d55

**Comment by vijaySamanuri** [comment]
Thank you Padmanabhan (@iamTheL) for reporting this issue.

Our Default log level is `debug` and we log many debug messages in the log files during `deploy` command execution. we also set the log files size limits using logback rolling policy but its not working as expected.

We will roll out a new patch having this fix soon.

In that patch you can expect the following:
1. default log level woudl be `info` and if you want set any other log level you can achieve through an environment variable `HYS_LOG_LEVEL`
2. fix for log file size limit along with compression for archives.

Meanwhile you can delete the old logs before executing any new hyscale command as workaround. We can help you to automate this in script if required.
